### ISSUE TITLE
Error on using Quizlet Learn

### ISSUE THREAD

**Issue by m23chaffee** [darthnithin/quizlet-modes#2]
Hello!
 
I'm trying to use your extension to get answers from Quizlet Learn since they've acquired Slader several weeks ago, keeping another alternative for Chegg for some time.

As I tried your Chrome extension, I encountered this bug. (Please see image below) .
![Capture](https://user-images.githubusercontent.com/89304338/130322237-8b1a45f5-9aba-411f-9d3c-802dff79571b.PNG)

If it is not yet part of your feature, I understand. I hope you could add it to your future updates. 

Thanks for checking out my report.

**Comment by darthnithin** [comment]
What is the url?

**Comment by darthnithin** [comment]
no update
