### ISSUE TITLE
(bookmarklet) issue when using quizlet learn/test/spell

### ISSUE THREAD

**Issue by hey000hey** [darthnithin/quizlet-modes#3]
whenever i try with the bookmarklet version, it says "Error: TypeError: Cannot read properties of undefined (reading 'map')"

also, instructions are very unclear about how to use the boomarklet version, could you briefly explain what the options mean? (like learn speed and some others) thanks!

**Comment by hey000hey** [comment]
same error for any quizlet set

**Comment by darthnithin** [comment]
the bookmarklet version is unsupported. Please use the extension version
